
// this is the response received from the server while fetching for top market movers in index spaces
/*const axios = require('axios');

const options = {
  method: 'GET',
  url: 'https://bloomberg-market-and-financial-news.p.rapidapi.com/market/get-movers',
  params: {
    id: 'nky:ind',
    template: 'INDEX'
  },
  headers: {
    'X-RapidAPI-Key': 'c4da87788cmsh56ed38777c9d63ap16e4dajsn4b66eb13ef5f',
    'X-RapidAPI-Host': 'bloomberg-market-and-financial-news.p.rapidapi.com'
  }
};

try {
	const response = await axios.request(options);
	console.log(response.data);
} catch (error) {
	console.error(error);
} */

let js={
  "active": [
    {
      "securityType": "Common Stock",
      "symbol": "9432",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "9432:jp",
      "tickerName": "9432:JP",
      "template": "Stock",
      "tinyName": "Nippon Telegraph & Telephone Corp",
      "name": "Nippon Telegraph & Telephone Corp",
      "watchlist": true,
      "resourceId": "9432:JP",
      "last": "170",
      "netChange": "-0",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-3",
      "yearHigh": "183",
      "dayHigh": "171",
      "volume": 221754800,
      "yearLow": "148",
      "dayLow": "169",
      "pctChangeYTD": "13",
      "pctChange": "-0.29"
    },
    {
      "securityType": "Common Stock",
      "symbol": "8306",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "8306:jp",
      "tickerName": "8306:JP",
      "template": "Stock",
      "tinyName": "Mitsubishi UFJ Financial Group Inc",
      "name": "Mitsubishi UFJ Financial Group Inc",
      "watchlist": true,
      "resourceId": "8306:JP",
      "last": "1204",
      "netChange": "-22",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-5",
      "yearHigh": "1353",
      "dayHigh": "1240",
      "volume": 88426100,
      "yearLow": "766",
      "dayLow": "1200",
      "pctChangeYTD": "35",
      "pctChange": "-1.83"
    },
    {
      "securityType": "Common Stock",
      "symbol": "9501",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "9501:jp",
      "tickerName": "9501:JP",
      "template": "Stock",
      "tinyName": "Tokyo Electric Power Co Holdings Inc",
      "name": "Tokyo Electric Power Co Holdings Inc",
      "watchlist": true,
      "resourceId": "9501:JP",
      "last": "752",
      "netChange": "-26",
      "lastPriceTime": 1702616400,
      "pctChange1M": "14",
      "yearHigh": "895",
      "dayHigh": "779",
      "volume": 84435500,
      "yearLow": "416",
      "dayLow": "747",
      "pctChangeYTD": "58",
      "pctChange": "-3.31"
    },
    {
      "securityType": "Common Stock",
      "symbol": "4755",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "4755:jp",
      "tickerName": "4755:JP",
      "template": "Stock",
      "tinyName": "Rakuten Group Inc",
      "name": "Rakuten Group Inc",
      "watchlist": true,
      "resourceId": "4755:JP",
      "last": "591",
      "netChange": "17",
      "lastPriceTime": 1702616400,
      "pctChange1M": "7",
      "yearHigh": "749",
      "dayHigh": "594",
      "volume": 33175000,
      "yearLow": "466",
      "dayLow": "573",
      "pctChangeYTD": "-1",
      "pctChange": "2.91"
    },
    {
      "securityType": "Common Stock",
      "symbol": "7203",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "7203:jp",
      "tickerName": "7203:JP",
      "template": "Stock",
      "tinyName": "Toyota Motor Corp",
      "name": "Toyota Motor Corp",
      "watchlist": true,
      "resourceId": "7203:JP",
      "last": "2600",
      "netChange": "29",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-10",
      "yearHigh": "2934",
      "dayHigh": "2624",
      "volume": 32057200,
      "yearLow": "1764",
      "dayLow": "2592",
      "pctChangeYTD": "43",
      "pctChange": "1.13"
    },
    {
      "securityType": "Common Stock",
      "symbol": "7201",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "7201:jp",
      "tickerName": "7201:JP",
      "template": "Stock",
      "tinyName": "Nissan Motor Co Ltd",
      "name": "Nissan Motor Co Ltd",
      "watchlist": true,
      "resourceId": "7201:JP",
      "last": "550",
      "netChange": "16",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-11",
      "yearHigh": "712",
      "dayHigh": "553",
      "volume": 31667300,
      "yearLow": "408",
      "dayLow": "543",
      "pctChangeYTD": "32",
      "pctChange": "2.94"
    },
    {
      "securityType": "Common Stock",
      "symbol": "4005",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "4005:jp",
      "tickerName": "4005:JP",
      "template": "Stock",
      "tinyName": "Sumitomo Chemical Co Ltd",
      "name": "Sumitomo Chemical Co Ltd",
      "watchlist": true,
      "resourceId": "4005:JP",
      "last": "334",
      "netChange": "10",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-16",
      "yearHigh": "501",
      "dayHigh": "334",
      "volume": 29037500,
      "yearLow": "323",
      "dayLow": "325",
      "pctChangeYTD": "-30",
      "pctChange": "3.15"
    },
    {
      "securityType": "Common Stock",
      "symbol": "7267",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "7267:jp",
      "tickerName": "7267:JP",
      "template": "Stock",
      "tinyName": "Honda Motor Co Ltd",
      "name": "Honda Motor Co Ltd",
      "watchlist": true,
      "resourceId": "7267:JP",
      "last": "1424",
      "netChange": "28",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-12",
      "yearHigh": "1821",
      "dayHigh": "1428",
      "volume": 28276600,
      "yearLow": "997",
      "dayLow": "1405",
      "pctChangeYTD": "41",
      "pctChange": "2.04"
    },
    {
      "securityType": "Common Stock",
      "symbol": "6902",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "6902:jp",
      "tickerName": "6902:JP",
      "template": "Stock",
      "tinyName": "Denso Corp",
      "name": "Denso Corp",
      "watchlist": true,
      "resourceId": "6902:JP",
      "last": "2090",
      "netChange": "-64",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-17",
      "yearHigh": "2614",
      "dayHigh": "2093",
      "volume": 25338600,
      "yearLow": "1597",
      "dayLow": "2076",
      "pctChangeYTD": "28",
      "pctChange": "-2.97"
    },
    {
      "securityType": "Common Stock",
      "symbol": "4689",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "4689:jp",
      "tickerName": "4689:JP",
      "template": "Stock",
      "tinyName": "LY Corp",
      "name": "LY Corp",
      "watchlist": true,
      "resourceId": "4689:JP",
      "last": "482",
      "netChange": "8",
      "lastPriceTime": 1702616400,
      "pctChange1M": "14",
      "yearHigh": "490",
      "dayHigh": "490",
      "volume": 23912500,
      "yearLow": "326",
      "dayLow": "476",
      "pctChangeYTD": "45",
      "pctChange": "1.77"
    }
  ],
  "laggards": [
    {
      "securityType": "Common Stock",
      "symbol": "4506",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "4506:jp",
      "tickerName": "4506:JP",
      "template": "Stock",
      "tinyName": "Sumitomo Pharma Co Ltd",
      "name": "Sumitomo Pharma Co Ltd",
      "watchlist": true,
      "resourceId": "4506:JP",
      "last": "423",
      "netChange": "-42",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-10",
      "yearHigh": "1031",
      "dayHigh": "462",
      "volume": 6273500,
      "yearLow": "415",
      "dayLow": "421",
      "pctChangeYTD": "-58",
      "pctChange": "-9.03"
    },
    {
      "securityType": "Common Stock",
      "symbol": "2002",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "2002:jp",
      "tickerName": "2002:JP",
      "template": "Stock",
      "tinyName": "Nisshin Seifun Group Inc",
      "name": "Nisshin Seifun Group Inc",
      "watchlist": true,
      "resourceId": "2002:JP",
      "last": "1922",
      "netChange": "-100",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-10",
      "yearHigh": "2338",
      "dayHigh": "1972",
      "volume": 2474600,
      "yearLow": "1503",
      "dayLow": "1910",
      "pctChangeYTD": "16",
      "pctChange": "-4.92"
    },
    {
      "securityType": "Common Stock",
      "symbol": "3382",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "3382:jp",
      "tickerName": "3382:JP",
      "template": "Stock",
      "tinyName": "Seven & i Holdings Co Ltd",
      "name": "Seven & i Holdings Co Ltd",
      "watchlist": true,
      "resourceId": "3382:JP",
      "last": "5487",
      "netChange": "-204",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-5",
      "yearHigh": "6619",
      "dayHigh": "5643",
      "volume": 5590800,
      "yearLow": "5162",
      "dayLow": "5483",
      "pctChangeYTD": "-3",
      "pctChange": "-3.58"
    },
    {
      "securityType": "Common Stock",
      "symbol": "2871",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "2871:jp",
      "tickerName": "2871:JP",
      "template": "Stock",
      "tinyName": "Nichirei Corp",
      "name": "Nichirei Corp",
      "watchlist": true,
      "resourceId": "2871:JP",
      "last": "3542",
      "netChange": "-129",
      "lastPriceTime": 1702616400,
      "pctChange1M": "8",
      "yearHigh": "3716",
      "dayHigh": "3623",
      "volume": 1282400,
      "yearLow": "2599",
      "dayLow": "3512",
      "pctChangeYTD": "23",
      "pctChange": "-3.51"
    },
    {
      "securityType": "Common Stock",
      "symbol": "4578",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "4578:jp",
      "tickerName": "4578:JP",
      "template": "Stock",
      "tinyName": "Otsuka Holdings Co Ltd",
      "name": "Otsuka Holdings Co Ltd",
      "watchlist": true,
      "resourceId": "4578:JP",
      "last": "5230",
      "netChange": "-190",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-6",
      "yearHigh": "5838",
      "dayHigh": "5385",
      "volume": 1997200,
      "yearLow": "3827",
      "dayLow": "5217",
      "pctChangeYTD": "21",
      "pctChange": "-3.51"
    },
    {
      "securityType": "Common Stock",
      "symbol": "9501",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "9501:jp",
      "tickerName": "9501:JP",
      "template": "Stock",
      "tinyName": "Tokyo Electric Power Co Holdings Inc",
      "name": "Tokyo Electric Power Co Holdings Inc",
      "watchlist": true,
      "resourceId": "9501:JP",
      "last": "752",
      "netChange": "-26",
      "lastPriceTime": 1702616400,
      "pctChange1M": "14",
      "yearHigh": "895",
      "dayHigh": "779",
      "volume": 84435500,
      "yearLow": "416",
      "dayLow": "747",
      "pctChangeYTD": "58",
      "pctChange": "-3.31"
    },
    {
      "securityType": "Common Stock",
      "symbol": "8316",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "8316:jp",
      "tickerName": "8316:JP",
      "template": "Stock",
      "tinyName": "Sumitomo Mitsui Financial Group Inc",
      "name": "Sumitomo Mitsui Financial Group Inc",
      "watchlist": true,
      "resourceId": "8316:JP",
      "last": "6760",
      "netChange": "-225",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-9",
      "yearHigh": "7849",
      "dayHigh": "6930",
      "volume": 18650100,
      "yearLow": "4702",
      "dayLow": "6747",
      "pctChangeYTD": "28",
      "pctChange": "-3.22"
    },
    {
      "securityType": "Common Stock",
      "symbol": "8308",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "8308:jp",
      "tickerName": "8308:JP",
      "template": "Stock",
      "tinyName": "Resona Holdings Inc",
      "name": "Resona Holdings Inc",
      "watchlist": true,
      "resourceId": "8308:JP",
      "last": "721",
      "netChange": "-23",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-8",
      "yearHigh": "898",
      "dayHigh": "737",
      "volume": 20841600,
      "yearLow": "586",
      "dayLow": "718",
      "pctChangeYTD": "-0",
      "pctChange": "-3.09"
    },
    {
      "securityType": "Common Stock",
      "symbol": "1332",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "1332:jp",
      "tickerName": "1332:JP",
      "template": "Stock",
      "tinyName": "Nissui Corp",
      "name": "Nissui Corp",
      "watchlist": true,
      "resourceId": "1332:JP",
      "last": "763",
      "netChange": "-23",
      "lastPriceTime": 1702616400,
      "pctChange1M": "8",
      "yearHigh": "821",
      "dayHigh": "779",
      "volume": 2580900,
      "yearLow": "517",
      "dayLow": "758",
      "pctChangeYTD": "39",
      "pctChange": "-2.96"
    },
    {
      "securityType": "Common Stock",
      "symbol": "8766",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "8766:jp",
      "tickerName": "8766:JP",
      "template": "Stock",
      "tinyName": "Tokio Marine Holdings Inc",
      "name": "Tokio Marine Holdings Inc",
      "watchlist": true,
      "resourceId": "8766:JP",
      "last": "3492",
      "netChange": "-105",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-0",
      "yearHigh": "3799",
      "dayHigh": "3590",
      "volume": 8194400,
      "yearLow": "2511",
      "dayLow": "3480",
      "pctChangeYTD": "24",
      "pctChange": "-2.92"
    }
  ],
  "leaders": [
    {
      "securityType": "Common Stock",
      "symbol": "9104",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "9104:jp",
      "tickerName": "9104:JP",
      "template": "Stock",
      "tinyName": "Mitsui OSK Lines Ltd",
      "name": "Mitsui OSK Lines Ltd",
      "watchlist": true,
      "resourceId": "9104:JP",
      "last": "4196",
      "netChange": "277",
      "lastPriceTime": 1702616400,
      "pctChange1M": "8",
      "yearHigh": "4655",
      "dayHigh": "4196",
      "volume": 10802400,
      "yearLow": "3045",
      "dayLow": "3967",
      "pctChangeYTD": "28",
      "pctChange": "7.07"
    },
    {
      "securityType": "Common Stock",
      "symbol": "9107",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "9107:jp",
      "tickerName": "9107:JP",
      "template": "Stock",
      "tinyName": "Kawasaki Kisen Kaisha Ltd",
      "name": "Kawasaki Kisen Kaisha Ltd",
      "watchlist": true,
      "resourceId": "9107:JP",
      "last": "5138",
      "netChange": "333",
      "lastPriceTime": 1702616400,
      "pctChange1M": "7",
      "yearHigh": "5833",
      "dayHigh": "5138",
      "volume": 11653200,
      "yearLow": "2555",
      "dayLow": "4873",
      "pctChangeYTD": "84",
      "pctChange": "6.93"
    },
    {
      "securityType": "Common Stock",
      "symbol": "6506",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "6506:jp",
      "tickerName": "6506:JP",
      "template": "Stock",
      "tinyName": "Yaskawa Electric Corp",
      "name": "Yaskawa Electric Corp",
      "watchlist": true,
      "resourceId": "6506:JP",
      "last": "5689",
      "netChange": "364",
      "lastPriceTime": 1702616400,
      "pctChange1M": "1",
      "yearHigh": "6859",
      "dayHigh": "5696",
      "volume": 2458400,
      "yearLow": "4065",
      "dayLow": "5425",
      "pctChangeYTD": "35",
      "pctChange": "6.84"
    },
    {
      "securityType": "Common Stock",
      "symbol": "9101",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "9101:jp",
      "tickerName": "9101:JP",
      "template": "Stock",
      "tinyName": "Nippon Yusen KK",
      "name": "Nippon Yusen KK",
      "watchlist": true,
      "resourceId": "9101:JP",
      "last": "3911",
      "netChange": "206",
      "lastPriceTime": 1702616400,
      "pctChange1M": "3",
      "yearHigh": "4446",
      "dayHigh": "3925",
      "volume": 9237300,
      "yearLow": "2858",
      "dayLow": "3745",
      "pctChangeYTD": "26",
      "pctChange": "5.56"
    },
    {
      "securityType": "Common Stock",
      "symbol": "4063",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "4063:jp",
      "tickerName": "4063:JP",
      "template": "Stock",
      "tinyName": "Shin-Etsu Chemical Co Ltd",
      "name": "Shin-Etsu Chemical Co Ltd",
      "watchlist": true,
      "resourceId": "4063:JP",
      "last": "5459",
      "netChange": "285",
      "lastPriceTime": 1702616400,
      "pctChange1M": "4",
      "yearHigh": "5565",
      "dayHigh": "5565",
      "volume": 12539100,
      "yearLow": "3158",
      "dayLow": "5391",
      "pctChangeYTD": "68",
      "pctChange": "5.51"
    },
    {
      "securityType": "Common Stock",
      "symbol": "5713",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "5713:jp",
      "tickerName": "5713:JP",
      "template": "Stock",
      "tinyName": "Sumitomo Metal Mining Co Ltd",
      "name": "Sumitomo Metal Mining Co Ltd",
      "watchlist": true,
      "resourceId": "5713:JP",
      "last": "4238",
      "netChange": "196",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-4",
      "yearHigh": "5515",
      "dayHigh": "4264",
      "volume": 2599200,
      "yearLow": "4004",
      "dayLow": "4076",
      "pctChangeYTD": "-9",
      "pctChange": "4.85"
    },
    {
      "securityType": "Common Stock",
      "symbol": "7272",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "7272:jp",
      "tickerName": "7272:JP",
      "template": "Stock",
      "tinyName": "Yamaha Motor Co Ltd",
      "name": "Yamaha Motor Co Ltd",
      "watchlist": true,
      "resourceId": "7272:JP",
      "last": "3764",
      "netChange": "164",
      "lastPriceTime": 1702616400,
      "pctChange1M": "0",
      "yearHigh": "4279",
      "dayHigh": "3770",
      "volume": 4041500,
      "yearLow": "2913",
      "dayLow": "3633",
      "pctChangeYTD": "25",
      "pctChange": "4.56"
    },
    {
      "securityType": "Common Stock",
      "symbol": "7270",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "7270:jp",
      "tickerName": "7270:JP",
      "template": "Stock",
      "tinyName": "Subaru Corp",
      "name": "Subaru Corp",
      "watchlist": true,
      "resourceId": "7270:JP",
      "last": "2560",
      "netChange": "110",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-7",
      "yearHigh": "3104",
      "dayHigh": "2568",
      "volume": 5103100,
      "yearLow": "1932",
      "dayLow": "2500",
      "pctChangeYTD": "27",
      "pctChange": "4.51"
    },
    {
      "securityType": "Common Stock",
      "symbol": "4004",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "4004:jp",
      "tickerName": "4004:JP",
      "template": "Stock",
      "tinyName": "Resonac Holdings Corp",
      "name": "Resonac Holdings Corp",
      "watchlist": true,
      "resourceId": "4004:JP",
      "last": "2946",
      "netChange": "116",
      "lastPriceTime": 1702616400,
      "pctChange1M": "9",
      "yearHigh": "2947",
      "dayHigh": "2947",
      "volume": 2555000,
      "yearLow": "1975",
      "dayLow": "2850",
      "pctChangeYTD": "46",
      "pctChange": "4.12"
    },
    {
      "securityType": "Common Stock",
      "symbol": "6326",
      "exchange": "Tokyo",
      "country": "Japan",
      "currency": "JPY",
      "resourceType": "Company",
      "fundamentalDataCurrency": "JPY",
      "resourceSubtype": "Public",
      "region": "APAC",
      "ticker": "6326:jp",
      "tickerName": "6326:JP",
      "template": "Stock",
      "tinyName": "Kubota Corp",
      "name": "Kubota Corp",
      "watchlist": true,
      "resourceId": "6326:JP",
      "last": "2086",
      "netChange": "82",
      "lastPriceTime": 1702616400,
      "pctChange1M": "-3",
      "yearHigh": "2421",
      "dayHigh": "2087",
      "volume": 5608300,
      "yearLow": "1777",
      "dayLow": "2016",
      "pctChangeYTD": "15",
      "pctChange": "4.07"
    }
  ]
}